#!/bin/bash

# cp git_static_hook_staging .git/hooks/pre-commit
# cp git_static_hook_staging .git/hooks/post-merge

# To make yuglify work
export PATH=/usr/local/bin:$PATH

# Change environment if you like
export DOGECAST_ENVIRONMENT="staging"
echo "Collating static files..."
./manage.py collectstatic --noinput -c > /dev/null

echo -e "\033[1;33mDone! Remember to restart the daemon if .py files have changed!\033[0m"
